### ISSUE TITLE
OL tools v22.[1-2] do not install on Eclipse JEE 2022-[06,09,12] (v4.[24,25,26]) because of org.eclipse.m2e.maven.runtime version requirement

### ISSUE THREAD

**Issue by titou10titou10** [OpenLiberty/open-liberty-tools#460] opened 2022-09-14 15:10 UTC
As the title says, open liberty tools v22.1 and v22.2 do not install on eclipse 2022-06 (v4.24), 2022-09 (v4.25) and 2022-12 (v4.26)

OL tools requires plugin`org.eclipse.m2e.maven.runtime [1.1.0,2.0.0)`that is not included with Eclipse JEE v2022-[06,09,12]
Eclipse JEE v2022-09 includes`org.eclipse.m2e.maven.runtime v3.8`

    Cannot complete the install because one or more required items could not be found.
      Software being installed: WebSphere® Application Server Liberty Tools 21.0.12.v2022-05-24_1817 (com.ibm.ws.st.liberty.tools.feature.group 21.0.12.v2022-05-24_1817)
      Missing requirement: Maven Tools for Liberty 1.2.2.v2022-05-24_1817 (com.ibm.etools.maven.liberty.integration 1.2.2.v2022-05-24_1817) requires 'osgi.bundle; org.eclipse.m2e.maven.runtime [1.1.0,2.0.0)' but it could not be found
      Cannot satisfy dependency:
        From: WebSphere® Application Server Liberty Tools 1.0.9.v2022-05-24_1817 (com.ibm.ws.st.liberty.tools.base.feature.group 1.0.9.v2022-05-24_1817)
        To: org.eclipse.equinox.p2.iu; com.ibm.etools.maven.liberty.integration [1.2.2.v2022-05-24_1817,1.2.2.v2022-05-24_1817]
      Cannot satisfy dependency:
        From: WebSphere® Application Server Liberty Tools 21.0.12.v2022-05-24_1817 (com.ibm.ws.st.liberty.tools.feature.group 21.0.12.v2022-05-24_1817)
        To: org.eclipse.equinox.p2.iu; com.ibm.ws.st.liberty.tools.base.feature.group [1.0.9.v2022-05-24_1817,1.0.9.v2022-05-24_1817]

OL tools v22.1/v22.2 have been downloaded from https://openliberty.io/start/#eclipse_developer_tools
Same error when trying to install OL tools via Eclipse Marketplace: "IBM Liberty Developer Tools 22.1" (p2 location=https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/updates/wdt/2022-03_comp/)

**Comment by mattcolegate** [comment] 2022-09-15 12:54
Hi @titou10titou10 , thanks for opening this. Initial investigation shows that 2022-09 and 2022-06 both have missing dependencies when trying to install WDT (of which OLT is a subset). Can I ask if it is possible for you to use 2022-03 until our next release at the end of November? Or is there needed function for you in the latest release of Eclipse?

**Comment by titou10titou10** [comment] 2022-09-15 13:05
@mattcolegate yw
I have to check for eclipse version but Eclipse 2022-03 is "quite old". We probably can stay with Eclipse 2022-03 we are currently using
Is the problem just a matter of relaxing the version requirement or is it deeper than that?

https://github.com/OpenLiberty/open-liberty-tools/blob/658b424fb17626b98b587c28e6255a588540d0d9/dev/com.ibm.etools.maven.liberty.integration/META-INF/MANIFEST.MF#L88

I can try to change this dependency version requirement, compile the plugin on my side and see hoe it goes

**Comment by mattcolegate** [comment] 2022-09-15 13:08
It's probably as you say, just relaxing the version requirement. As we're now committing to two releases a year it's inevitable that we will get these kind of errors as Eclipse moves beneath us.

**Comment by titou10titou10** [comment] 2022-09-16 17:04
> Can I ask if it is possible for you to use 2022-03 until our next release at the end of November? Or is there needed function for you in the latest release of Eclipse?
> As we're now committing to two releases a year it's inevitable that we will get these kind of errors as Eclipse moves beneath us.

Hummm....
Today, this means that users of OLP will be stuck with a version of Eclipse that will be 8 months old (March -> November)
I can understand the strategy for publishing a new version twice a year. 
IMHO for most "minor" bugs this is okay, but for bugs  like this one where you can not even install the plugin, IMHO "intermediate/emergency" releases should be published. 8 months can be looong

**Comment by titou10titou10** [comment] 2022-09-16 21:23
When I change this

https://github.com/OpenLiberty/open-liberty-tools/blob/658b424fb17626b98b587c28e6255a588540d0d9/dev/com.ibm.etools.maven.liberty.integration/META-INF/MANIFEST.MF#L88

into 

        Require-Bundle: org.eclipse.m2e.maven.runtime,

and build the plugin, it installs in Eclipse v2022-09 / 4.25 without problem and it seem to work as expected

**Comment by JanSerneels** [comment] 2022-09-23 10:11
gradle build didn't work for me after clone, so i edited the jar file inside the zip file instead.

openlibertytools-22.1.zip
   com.ibm.etools.maven.liberty.integration_1.2.2.v2022-05-24_1817.jar

After editing MANIFEST.MF as you suggest i tried to install openliberty-tools in eclipse 2022-09-EE.

Seems the version contraint is still active somehow. What did i miss?

This is the error message i get  : 

Cannot complete the install because one or more required items could not be found.
  Software being installed: WebSphere® Application Server Liberty Tools 21.0.12.v2022-05-24_1817 (com.ibm.ws.st.liberty.tools.feature.group 21.0.12.v2022-05-24_1817)
  Missing requirement: Maven Tools for Liberty 1.2.2.v2022-05-24_1817 (com.ibm.etools.maven.liberty.integration 1.2.2.v2022-05-24_1817) requires 'osgi.bundle; org.eclipse.m2e.maven.runtime [1.1.0,2.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: WebSphere® Application Server Liberty Tools 1.0.9.v2022-05-24_1817 (com.ibm.ws.st.liberty.tools.base.feature.group 1.0.9.v2022-05-24_1817)
    To: org.eclipse.equinox.p2.iu; com.ibm.etools.maven.liberty.integration [1.2.2.v2022-05-24_1817,1.2.2.v2022-05-24_1817]
  Cannot satisfy dependency:
    From: WebSphere® Application Server Liberty Tools 21.0.12.v2022-05-24_1817 (com.ibm.ws.st.liberty.tools.feature.group 21.0.12.v2022-05-24_1817)
    To: org.eclipse.equinox.p2.iu; com.ibm.ws.st.liberty.tools.base.feature.group [1.0.9.v2022-05-24_1817,1.0.9.v2022-05-24_1817]


[openlibertytools-22.1-janSerneels.zip](https://github.com/OpenLiberty/open-liberty-tools/files/9632732/openlibertytools-22.1-janSerneels.zip)

**Comment by titou10titou10** [comment] 2022-09-23 12:34
> gradle build didn't work for me after clone, so i edited the jar file inside the zip file instead.

What went wrong with the gradle build? To build, I just change the location of the eclipse SDK . From 

https://github.com/OpenLiberty/open-liberty-tools/blob/658b424fb17626b98b587c28e6255a588540d0d9/dev/gradle.properties#L12-L14

to

    # Target platform : Oxygen
    eclipse.sdk.url=https://archive.eclipse.org/eclipse/downloads/drops4/R-4.7.3a-201803300640/eclipse-SDK-4.7.3a-linux-gtk-x86_64.tar.gz
    eclipse.target.platform.url=https://archive.eclipse.org/technology/epp/downloads/release/oxygen/3a/eclipse-jee-oxygen-3a-linux-gtk-x86_64.tar.gz

I upload my build of the plugin: [openlibertytools-22.2.v2022-09-16_1548.zip](https://github.com/OpenLiberty/open-liberty-tools/files/9633614/openlibertytools-22.2.v2022-09-16_1548.zip)

**Comment by JanSerneels** [comment] 2022-09-23 14:19
- the gradle build had a problem dowloading eclipse sdk, i will try your settings later. thnx
- your version of the tools gets installed in eclipse 2022-09-EE now. 
- made a simple faceted project (dynamic web module 5.0, java 17) but am not able to link the liberty runtime with this project. Eclipse states that the servlet 5.0 application cannot be deployed on the liberty 22.0.0.9 with jakartaee-9.1 feature. In eclipse 2022-03 i have the same issue. When i drop the war in the dropin folder on the server it seems to work correctly though. But the only thing missing then is easy eclipse integration ;-)

 What is your assessment? Is the problem in my eclipse project / openlibertytools / eclipse ?

       I filed a bug report already a time ago to eclipse, but am not sure that i was correct.
                 https://bugs.eclipse.org/bugs/show_bug.cgi?id=579904

**Comment by JanSerneels** [comment] 2022-09-29 06:43
Apparently wtp does not support Dynamic Web Project facet 5.0 in eclipse.

https://github.com/OpenLiberty/open-liberty-tools/wiki/22.1-Known-Issues

**Comment by titou10titou10** [comment] 2022-09-29 12:31
@JanSerneels please do not hijack this ticket. P
lease open another one as this is a totally different problem as the original one
Thanks

**Comment by titou10titou10** [comment] 2022-11-25 15:22
OL tool 22.2 is out but it seems this bug is still present..

**Comment by mattcolegate** [comment] 2022-11-25 15:45
@titou10titou10 Unfortunately we were unable to contain this work for the 22.2 release. We will look to update this soon, and I will be pushing for a fix process to be identified so that we do not have this dragging on for another six months. 22.2 is targeted at 2022-03 Eclipse. I'm sorry I forgot to update you on this earlier.

**Comment by titou10titou10** [comment] 2022-11-25 17:46
wow!!! OLP tools v22.2 targets Eclipse 2022-03 AT MOST ???
This means that if you want to use OLP tools  with Eclipse, you are stuck with Eclipse v2022-03 or earlier, a version  that will be 15 months old when v23.1 will be out, ie in 6 months?  
What you are saying is that wee need to wait fo Eclipse 2023-06 to be able to use the OLP tools plugin again? wow

Sorry but IMHO this is clearly not acceptable

As said before, this is not a minor bug. this "simple" bug blocks you to install the whole plugin

I can create a PR that just remove the maven plugin version restriction (see comments above as I was able to install the plugin) as it is a one line change and it makes the plugin install and "work", but I'm not confident enough to says that this is the way to fix the bug

**Comment by mattcolegate** [comment] 2022-11-29 14:16
Hi @titou10titou10,

One of our test team members has come up with a potential workaround - Download Eclipse 2022-03, install OLT 22.2 on that, then upgrade to Eclipse 2022-09. Can you give that a whirl and see if that might be a solution?

**Comment by rosczja** [comment] 2022-12-06 13:45
Hi @mattcolegate , I did try this in the past. The problem is that m2e plugins are then not upgraded to version 2. If you need functionality in the newer version you are again stuck.

So I think the only viable option is to make OLT compatible with m2e >= 2.0.

**Comment by titou10titou10** [comment] 2022-12-07 18:44
As for v22.1 before, I build my own version of v22.2 after removing the "problematic" equinox dependency to "org.eclipse.m2e.maven.runtime v[1.1.0,2.0.0)" as described here: 

  https://github.com/OpenLiberty/open-liberty-tools/issues/460#issuecomment-1249828500

It installs on my freshly installed Eclipse v2022-12 JEE (v4.26). It seems to work so far, at least for my needs of the plugin
Of course there is no guarantee it works in all use cases as I have no idea of the implications of the removal of the dependencies if what I did is the right thing to do to fix the problem

[openlibertytools-22.2.v2022-12-07_1446.zip](https://github.com/OpenLiberty/open-liberty-tools/files/10179063/openlibertytools-22.2.v2022-12-07_1446.zip)

**Comment by mattcolegate** [comment] 2022-12-08 12:31
Thanks @rosczja and @titou10titou10. @titou10titou10, are you able to put your change up as a pull request?

**Comment by titou10titou10** [comment] 2022-12-08 13:29
@mattcolegate , as explained before,I have no problem creating a PR with this one line change but I'm not confident at all that this the only change that has to be done, maybe some deeper changes have to be made for the plugin to interact with the latest version of the maven plugin

At least the change allows the plugin to install on the 3 latest version of Eclipse but if the version restriction is present in the code, I guess this is for a reason. 

Removing the deployment restriction does not guarantee that the rest of the code (that was OK with `org.eclipse.m2e.maven.runtime;bundle-version="[1.1.0,2.0.0)"`) is still adapted to work with`"org.eclipse.m2e.maven.runtime`" v3.8+, version included with Eclipse JEE v2022-06+

**Comment by titou10titou10** [comment] 2022-12-08 13:52
PR #466 created

**Comment by pnickoll** [comment] 2023-01-16 12:47
FYI: We have found there are more changes required in order to get this to work but we are working on them and expect to have them in the next release. Many thanks for the PR - I will get that part merged in.

**Comment by titou10titou10** [comment] 2023-04-06 13:16
Until the official build is done, here are the OpenLiberty tools compiled from the integration branch that install on eclipse 2023-03

Note that I did not change any file from the integration branch and it installs flawlessly on eclipse v2023-03

[openlibertytools-23.1.v2023-03-06_1555.zip](https://github.com/OpenLiberty/open-liberty-tools/files/11170959/openlibertytools-23.1.v2023-03-06_1555.zip)

**Comment by pnickoll** [comment] 2024-02-05 11:51
This should be fixed now in WDT 23.1. Please reopen if you still have issues.

**Closed by pnickoll** 2024-02-05 11:51 UTC
