### ISSUE TITLE
NPE in WebSphereRuntimeLocator

### ISSUE THREAD

**Issue by andre-doherty** [OpenLiberty/open-liberty-tools#388] opened 2020-04-08 15:40 UTC
Hello,

It occurs quite frequently that i meet this runtime error : 

!ENTRY com.ibm.ws.st.core 4 0 2020-04-07 12:06:33.158
!MESSAGE Could not find runtime
!STACK 0
java.lang.NullPointerException
	at com.ibm.ws.st.core.internal.WebSphereRuntimeLocator.getRuntimeFromDir(WebSphereRuntimeLocator.java:93)
	at com.ibm.ws.st.liberty.buildplugin.integration.internal.AbstractLibertyRuntimeProvider.getWSRuntime(AbstractLibertyRuntimeProvider.java:280)
	at com.ibm.ws.st.liberty.buildplugin.integration.internal.AbstractLibertyRuntimeProvider.getUserDirectory(AbstractLibertyRuntimeProvider.java:245)
	at com.ibm.ws.st.liberty.buildplugin.integration.internal.AbstractLibertyRuntimeProvider.getWebSphereServerInfo(AbstractLibertyRuntimeProvider.java:115)
	at com.ibm.ws.st.core.internal.config.ConfigUtils.getServerFromRuntimeProviders(ConfigUtils.java:392)
	at com.ibm.ws.st.core.internal.config.ConfigUtils.getServer(ConfigUtils.java:354)
	at com.ibm.ws.st.core.internal.config.validation.DOMModelValidationContext.getConfigFile(DOMModelValidationContext.java:96)
	at com.ibm.ws.st.core.internal.config.validation.AbstractConfigurationValidator.processServer(AbstractConfigurationValidator.java:413)
	at com.ibm.ws.st.core.internal.config.validation.AbstractConfigurationValidator.processDocument(AbstractConfigurationValidator.java:387)
	at com.ibm.ws.st.core.internal.config.validation.AbstractConfigurationValidator.validate(AbstractConfigurationValidator.java:191)
	at com.ibm.ws.st.core.internal.config.validation.AbstractConfigurationValidator.validate(AbstractConfigurationValidator.java:144)
	at com.ibm.ws.st.core.internal.config.validation.ConfigurationValidator.validate(ConfigurationValidator.java:136)
	at org.eclipse.wst.validation.Validator$V2.validate(Validator.java:1178)
	at org.eclipse.wst.validation.internal.ValManager.validate(ValManager.java:704)
	at org.eclipse.wst.validation.internal.ValManager$1.visit(ValManager.java:665)
	at org.eclipse.wst.validation.internal.ValManager.accept(ValManager.java:810)
	at org.eclipse.wst.validation.internal.ValManager.validate(ValManager.java:669)
	at org.eclipse.wst.validation.internal.ValBuilderJob$Visitor.visit(ValBuilderJob.java:299)
	at org.eclipse.core.internal.resources.Resource.lambda$1(Resource.java:117)
	at org.eclipse.core.internal.resources.Resource.lambda$0(Resource.java:85)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:85)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:135)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:55)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:117)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:105)
	at org.eclipse.wst.validation.internal.ValBuilderJob.fullBuild(ValBuilderJob.java:219)
	at org.eclipse.wst.validation.internal.ValBuilderJob.run(ValBuilderJob.java:178)
	at org.eclipse.wst.validation.internal.ValBuilderJob.runInWorkspace(ValBuilderJob.java:126)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

It looks like that in some situations runtime.getLocation may be null.

This occurs vers possibly when some bogus and hidden server configuration are left in the workspace ....

In this case it becomes impossible to create a runtime and server and the only cure is to start over with a fresh workspace.

Thanks a lot !

André

Could you please add an extra test so that the server creation

**Comment by andre-doherty** [comment] 2020-04-08 15:53
The behavior may be reproduced by creating a httpPreview server.

When you do this a runtime entry is added to the org.eclipse.wst.server.core.prefs file (located in .metadata\.plugins\org.eclipse.core.runtime\.settings\) : 

<runtime id\="HTTP Preview" name\="HTTP Preview" runtime-type-id\="org.eclipse.wst.server.preview.runtime" timestamp\="0"/>\r\n

As a matter of fact there is no such thing as a location attribute. 

Removing this entry - which remains even if the server has been removed - manually and restarting eclipse "fix" the behavior : i am able to proceed with the server creation

**Comment by josephca** [comment] 2020-04-08 19:00
@eharris369 any clue?

**Comment by eharris369** [comment] 2020-04-08 20:19
I could not reproduce this. I tried the HTTP preview server and no NPE. I created a fix anyway since it seems harmless: https://github.com/OpenLiberty/open-liberty-tools/pull/389. What version of Eclipse are you using?

**Comment by andre-doherty** [comment] 2020-04-08 21:15
I am using STS 4.4.0.Release3 (build on eclipse 4.14.0.v20191210-0610). However the issue has been there for a while ...
I was just able to reproduce the case from a fresh workspace.

Create a HttpPreview server,, deploy a WebProject, watch the org.eclipse.wst.server.core.prefs file for the HTTP Preview entry. 
You might need to restart eclipse.

When it s there import a maven project using the liberty-maven-plugin.
"Create runtime and server" from the Runtime Explorer view should trigger the NPE

**Comment by eharris369** [comment] 2020-04-09 15:18
I tried again but could not reproduce. I have put the fix in anyway. You can get development builds of Open Liberty Tools here: https://openliberty.io/downloads/
- Under the Download Package heading click Eclipse Developer Tools
- Scroll down to the Development builds heading
A build with the fix should happen tonight.

**Comment by andre-doherty** [comment] 2020-04-09 18:11
Thanks a lot!

I will try it out and give you a feedback (should be OK considering the change in the code). 

Regards 

André

**Comment by andre-doherty** [comment] 2020-04-22 16:17
Hi there.
I have tested the openlibertytools-20.0.0.6.v2020-04-14_0907 build with success.

Thanks you very much.

**Comment by eharris369** [comment] 2020-04-22 16:27
Closing the issue since the fix was verified by the originator.

**Closed by eharris369** 2020-04-22 16:27 UTC
